#!/usr/bin/ruby
require 'rubygems'
require 'rubygame'
require 'matrix'
require 'pp'

include Rubygame

resolution = [640, 480]

@screen = Screen.open resolution, 0, [HWSURFACE, DOUBLEBUF]
@screen.title = "JumpJump"
#@screen.show_cursor = false

unless @screen.respond_to? :draw_box
  puts "Don't have SDL_gfx available, can't use draw_box"
  puts "Exiting..."
  exit 1
end

class Player
  include Sprites::Sprite

  def initialize
    super()

    color = [ 0xc0, 0x80, 0x40]
    @image = Surface.new [30,30]
    @image.draw_box_s [0,0], [30,30], color
    @rect = @image.make_rect
    @velocity = [0, 2] #gravity
  end

  def vel_add vel
    @velocity[0] += vel[0]
    @velocity[1] += vel[1]
  end

  def vel_inv
    print "Was: "
    pp @velocity
    @velocity[0] = -1 * @velocity[0]
    @velocity[1] = -1 * @velocity[1]
    print "Now: "
    pp @velocity
  end

  def update seconds_passed, walls
    old_velocity = @velocity
    x, y = @velocity
    factor = 500 * seconds_passed
    x *= factor
    y *= factor
    @rect.move! x,y

    # undo x and y separately so you can move without jumping
    @rect.move! 0, -1.0 * y if collides? walls # undo gravity
    @rect.move! -1.0 * x, 0 if collides? walls # undo sideways movement
  end

  def draw on_surface
    @rect.clamp! on_surface.make_rect
    @image.blit on_surface, @rect
  end

  def collides? group
    collide_group(group) != []
  end
end

class Wall
  include Sprites::Sprite
  def initialize pos
    super()

    color = [ 0xc0, 0x10, 0x10]
    @image = Surface.new [80,10]
    @image.draw_box_s [0,0], [80,10], color
    @rect = @image.make_rect
    @rect.topleft = pos
  end

  def draw on_surface
    @image.blit on_surface, @rect
  end
end

@background = Surface.new resolution
@background.blit @screen,[0,0]

@clock = Clock.new
@clock.target_framerate = 120
@clock.enable_tick_events

@sprites=Sprites::Group.new
@walls=Sprites::Group.new
Sprites::UpdateGroup.extend_object @sprites
Sprites::UpdateGroup.extend_object @walls

@player = Player.new
@sprites << @player

@walls << Wall.new([400,400])
@walls << Wall.new([300,300])
@walls << Wall.new([200,200])
@walls << Wall.new([100,100])
@walls.draw @screen

@event_queue = EventQueue.new
@event_queue.enable_new_style_events #enables rubygame 3.0

should_run = true
while should_run
  seconds_passed = @clock.tick().seconds

  @event_queue.each do |event|
    puts event
    case event
    when Events::QuitRequested
      should_run = false
    when Events::KeyPressed 
      @player.vel_add [-1,0] if event.key == :left
      @player.vel_add [ 1,0] if event.key == :right
      @player.vel_add [0,-4] if event.key == :up
    when Events::KeyReleased 
      @player.vel_add [ 1,0] if event.key == :left
      @player.vel_add [-1,0] if event.key == :right
      @player.vel_add [0,4] if event.key == :up
    end
  end

  @sprites.undraw @screen, @background
  @sprites.update seconds_passed, @walls
  @sprites.draw @screen
  @screen.flip
end

